[build]
  command = """
    python -m pip install --upgrade pip
    pip install -r requirements.txt --no-cache-dir
    mkdir -p src/config
    wget https://pjreddie.com/media/files/yolov3.weights -O src/config/yolov3.weights || wget https://github.com/patrick013/Object-Detection---Yolov3/raw/master/model/yolov3.weights -O src/config/yolov3.weights
  """
  publish = "build"

[build.environment]
  PYTHON_VERSION = "3.8.12"
  PIP_DISABLE_PIP_VERSION_CHECK = "1"
  PYTHONUNBUFFERED = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 